_core:
  default_config_hash: 4bQlG9nX40H6RYr1oMGvC0OQ_EGyNS_075_dl8JcrmE
container_width: 1260
header_width: header_width_contained
main_width: main_width_contained
footer_width: footer_width_contained
all_icons_show: 1
facebook_url: 'https://www.facebook.com/idewdot'
twitter_url: 'https://twitter.com/dewdots'
instagram_url: 'https://www.instagram.com/google'
linkedin_url: 'https://in.linkedin.com/company/google'
youtube_url: 'https://www.youtube.com/@dev_tut'
whatsapp_url: ''
github_url: 'https://github.com/dewdot'
telegram_url: ''
vimeo_url: ''
highlight_author_comment: 0
node_author_pic: 0
node_tags: 0
copyright_text: 1
scrolltotop_on: 1
css_extra: 0
css_code: ''
