commerce_payment.commerce_payment_gateway.plugin.razorpay:
  type: commerce_payment_gateway_configuration
  mapping:
    key_id:
      type: string
      label: 'Key ID'
    key_secret:
      type: string
      label: 'Key Secret'
    payment_action:
      type: sequence
      label: 'Payment Action'
      sequence:
        type: string
