<?php

/**
 * Implements hook_page_attachments_alter().
 */
function reactshop_theme_page_attachments_alter(array &$attachments) {
  // Use the dev library if we're developing locally.
  if (in_array('reactshop/react_app_dev', $attachments['#attached']['library']) && file_exists(__DIR__ . '/js/dist_dev')) {
    $index = array_search('react_example_theme/react_app_dev', $attachments['#attached']['library']);
    $attachments['#attached']['library'][$index] = 'reactshop/react_app_dev';
  }
}